[package]
name = "bergbuch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"

[profile.profiler]
inherits = "release"
debug = true

[features]
compliant = []
